services:
    app:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
        container_name: reut-app
        image: reut:latest
        ports:
            - "8000:8000"
        env_file:
            - .env.docker.local
        volumes:
            - ./.env:/app/.env.docker.local
        depends_on:
            - db

    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: reut_simde
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
